FROM golang:1.18.0 as builder

WORKDIR /go/app

COPY ./pkg/ ./pkg/
COPY ./cmd/credit/ ./cmd/credit/
COPY ./go.mod  ./

ARG CGO_ENABLED=0
ARG GOOS=linux
ARG GOARCH=amd64
RUN go mod tidy
RUN cd cmd/credit && \
    go build \
    -o /go/app/bin/main \
    -ldflags '-s -w'

EXPOSE 8080

ENTRYPOINT ["/go/app/bin/main"]