name: Go CI Credit Application

on:
  push:
    branches: [ feature/issue31 ]
    paths: 
      - 'cmd/credit'
      - 'pkg'
      - 'package/credit'
      - '.github/workflows/build-credit.yml'

jobs:
  build:
    
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout manifest repo
      uses: actions/checkout@v2
      with:
        repository: nautible/nautible-app-ms-payment-manifest
        path: nautible-app-ms-payment-manifest
        token: ${{ secrets.PAT }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-role
        aws-region: ap-northeast-1
    - name: Login to Amazon public ECR
      id: login-ecr
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/nautible
    - name: Payment Build, tag, and push image to Amazon ECR
      id: build-image-service
      env:
        DOCKER_BUILDKIT: 1
        ECR_REGISTRY: public.ecr.aws/nautible
        ECR_REPOSITORY: nautible-app-ms-payment-credit
      run: |
        cd $GITHUB_WORKSPACE
        docker build --cache-from=$ECR_REGISTRY/$ECR_REPOSITORY:latest --build-arg BUILDKIT_INLINE_CACHE=1 -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./package/credit/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    - name: pull request
      id: pull-request
      env:
        tag: update-image-feature-${{ github.sha }}
        token: ${{ secrets.PAT }}
      run: |
        cd $GITHUB_WORKSPACE/nautible-app-ms-payment-manifest
        git checkout -b $tag
        sed -i 's/image: public.ecr.aws\/nautible\/nautible-app-ms-payment-credit:\(.*\)/image: public.ecr.aws\/nautible\/nautible-app-ms-payment-credit:'$IMAGE_TAG'/' ./credit/base/payment-credit-deploy.yaml 
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "update manifest"
        git push --set-upstream origin $tag
        curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $token" "https://api.github.com/repos/nautible/nautible-app-ms-payment-manifest/pulls" -d '{"title": "new image deploy request", "head": "nautible:'$tag'", "base": "main"}' -o /dev/null -w 'httpstatus:%{http_code}\n' -s
