name: Go CI Payment and Credit Application

on:
  push:
    branches: ['develop', 'feature/*', 'hotfix/*']
    paths:
      - 'cmd/**'
      - 'pkg/**'
      - 'package/**'
      - '.github/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    environment: develop # for azure oidc

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Checkout manifest repo
        uses: actions/checkout@v3
        with:
          repository: nautible/nautible-app-ms-payment-manifest
          path: nautible-app-ms-payment-manifest
          token: ${{ secrets.PAT }}

      # AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/nautible-dev-githubactions-ecr-access-role
          aws-region: ap-northeast-1
        continue-on-error: true

      - name: output step context_aws
        run: echo $CONTEXT
        env:
          CONTEXT: ${{ toJSON(steps.login-ecr) }}

      - name: login-ecr when command success
        uses: ./.github/workflows/aws.yml
        if: steps.login-ecr.outcome == 'success'

      - name: login-ecr when command failure
        run: echo "result - aws ecr login failure"
        if: steps.login-ecr.outcome == 'failure'

        # Azure
      - name: Login via Azure CLI
        id: login-acr
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login Azure Acr
        id: login-azure-acr
        run: |
          az acr login -n nautibledevacr
        continue-on-error: true

      - name: output step context_azure
        run: echo $CONTEXT
        env:
          CONTEXT: ${{ toJSON(steps.login-azure-acr) }}

      - name: login-azure-acr when command success
        uses: ./.github/workflows/azure.yml
        if: steps.login-azure-acr.outcome == 'success'

      - name: login-azure-acr when command failure
        run: echo "result - azure acr login failure"
        if: steps.login-azure-acr.outcome == 'failure'

      # pullrequest
      - name: update feature branch image tag
        id: update-feature-branch-image-tag
        if: startsWith(github.ref_name, 'feature/')
        env:
          TOKEN: ${{ secrets.PAT }}
          BRANCH: ${{ github.ref_name }}
          APP_NAME: payment
          ACR_REGISTRY: nautibledevacr.azurecr.io
        run: |
          cd $GITHUB_WORKSPACE/nautible-app-ms-$APP_NAME-manifest
          HTTP_STATUS=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: token $TOKEN" https://api.github.com/repos/nautible/nautible-app-ms-$APP_NAME-manifest/branches/$BRANCH -o /dev/null -w '%{http_code}\n' -s)
          if [ "$HTTP_STATUS" != '200' ]; then
            echo 'couldnt find remote branch. skip update manifest.'
            exit 0
          fi
          git fetch origin $BRANCH && git checkout $BRANCH
          sed -i 's/image: public.ecr.aws\/nautible\/nautible-app-ms-'$APP_NAME':\(.*\)/image: public.ecr.aws\/nautible\/nautible-app-ms-'$APP_NAME':'$IMAGE_TAG'/' ./base/$APP_NAME-deploy.yaml 
          sed -i 's/image: public.ecr.aws\/nautible\/nautible-app-ms-'$APP_NAME'-credit:\(.*\)/image: public.ecr.aws\/nautible\/nautible-app-ms-'$APP_NAME'-credit:'$IMAGE_TAG'/' ./base/$APP_NAME-credit-deploy.yaml 
          sed -i 's/image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}\/nautible-app-ms-'$APP_NAME':\(.*\)/image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}\/nautible-app-ms-'$APP_NAME':'$IMAGE_TAG'/' ./overlays/azure/dev/$APP_NAME-deploy.yaml 
          sed -i 's/image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}\/nautible-app-ms-credit:\(.*\)/image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}\/nautible-app-ms-credit:'$IMAGE_TAG'/' ./overlays/azure/dev/$APP_NAME-credit-deploy.yaml 
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "update manifest"
          git push

      - name: pull request
        id: pull-request
        if: github.ref_name == 'develop' || startsWith(github.ref_name, 'hotfix/')
        env:
          TOKEN: ${{ secrets.PAT }}
          BRANCH: ${{ github.ref_name }}
          TAG: update-image-feature-${{ github.sha }}
          APP_NAME: payment
          ACR_REGISTRY: nautibledevacr.azurecr.io
        run: |
          cd $GITHUB_WORKSPACE/nautible-app-ms-$APP_NAME-manifest
          git fetch origin $BRANCH && git checkout $BRANCH
          git checkout -b $TAG $BRANCH
          sed -i 's/image: public.ecr.aws\/nautible\/nautible-app-ms-'$APP_NAME':\(.*\)/image: public.ecr.aws\/nautible\/nautible-app-ms-'$APP_NAME':'$IMAGE_TAG'/' ./base/$APP_NAME-deploy.yaml 
          sed -i 's/image: public.ecr.aws\/nautible\/nautible-app-ms-'$APP_NAME'-credit:\(.*\)/image: public.ecr.aws\/nautible\/nautible-app-ms-'$APP_NAME'-credit:'$IMAGE_TAG'/' ./base/$APP_NAME-credit-deploy.yaml 
          sed -i 's/image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}\/nautible-app-ms-'$APP_NAME':\(.*\)/image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}\/nautible-app-ms-'$APP_NAME':'$IMAGE_TAG'/' ./overlays/azure/dev/$APP_NAME-deploy.yaml 
          sed -i 's/image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}\/nautible-app-ms-credit:\(.*\)/image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}\/nautible-app-ms-credit:'$IMAGE_TAG'/' ./overlays/azure/dev/$APP_NAME-credit-deploy.yaml 
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "update manifest"
          git push --set-upstream origin $TAG
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $TOKEN" "https://api.github.com/repos/nautible/nautible-app-ms-$APP_NAME-manifest/pulls" -d '{"title": "new image deploy request", "head": "nautible:'$TAG'", "base": "'$BRANCH'"}' -o /dev/null -w 'httpstatus:%{http_code}\n' -s
